
const NOT_FOUND = 404
const VALIDATION_ERROR = 400
const UNATHORIZED = 401
const FORBIDDEN = 403
const SERVER_ERROR = 500

export { NOT_FOUND, VALIDATION_ERROR, UNATHORIZED, FORBIDDEN, SERVER_ERROR }
